-- ### 1. CREACIÓN DE TABLAS (SIN LLAVES FORÁNEAS)
CREATE TABLE CENTRO (
    ID_CENTRO INTEGER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL
);
ALTER TABLE CENTRO ADD CONSTRAINT CENTRO_PK PRIMARY KEY (ID_CENTRO);

CREATE TABLE CORRELATIVO (
    ID_CORRELATIVO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    NO_EXAMEN INTEGER NOT NULL
);
ALTER TABLE CORRELATIVO ADD CONSTRAINT CORRELATIVO_PK PRIMARY KEY (ID_CORRELATIVO);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INTEGER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CODIGO INTEGER NOT NULL
);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (ID_DEPARTAMENTO);

CREATE TABLE ESCUELA (
    ID_ESCUELA INTEGER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    ACUERDO VARCHAR2(100) NOT NULL
);
ALTER TABLE ESCUELA ADD CONSTRAINT ESCUELA_PK PRIMARY KEY (ID_ESCUELA);

CREATE TABLE PREG (
    ID_PREG INTEGER NOT NULL,
    PREG_TEXTO VARCHAR2(500) NOT NULL,
    RES VARCHAR2(100) NOT NULL,
    RES1 VARCHAR2(500) NOT NULL,
    RES2 VARCHAR2(500) NOT NULL,
    -- MODIFICADO: Se permite que RES3 y RES4 sean nulas
    RES3 VARCHAR2(500),
    RES4 VARCHAR2(500)
);
ALTER TABLE PREG ADD CONSTRAINT PREG_PK PRIMARY KEY (ID_PREG);

CREATE TABLE PREG_PRACT (
    ID_PREG_PRACT INTEGER NOT NULL,
    PREG_TEXTO VARCHAR2(500) NOT NULL,
    PUNTEO INTEGER NOT NULL
);
ALTER TABLE PREG_PRACT ADD CONSTRAINT PREG_PRACT_PK PRIMARY KEY (ID_PREG_PRACT);

-- ### 2. CREACIÓN DE TABLAS DEPENDIENTES
CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO INTEGER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CODIGO INTEGER NOT NULL,
    DEPARTAMENTO_ID_DEPARTAMENTO INTEGER NOT NULL
);
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY (ID_MUNICIPIO);

CREATE TABLE UBICACION (
    ESCUELA_ID_ESCUELA INTEGER NOT NULL,
    CENTRO_ID_CENTRO INTEGER NOT NULL
);
ALTER TABLE UBICACION ADD CONSTRAINT UBICACION_PK PRIMARY KEY (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO);

CREATE TABLE REGISTRO (
    ID_REGISTRO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    TIPO_TRAMITE VARCHAR2(100) NOT NULL,
    TIPO_LICENCIA VARCHAR2(100) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(100),
    GENERO VARCHAR2(100) NOT NULL,
    MUNICIPIO_ID_MUNICIPIO INTEGER NOT NULL,
    UBICACION_ESCUELA_ID INTEGER NOT NULL,
    UBICACION_CENTRO_ID INTEGER NOT NULL
);
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_PK PRIMARY KEY (ID_REGISTRO);

CREATE TABLE EXAMEN (
    ID_EXAMEN INTEGER NOT NULL,
    REGISTRO_ID_REGISTRO INTEGER NOT NULL,
    CORRELATIVO_ID_CORRELATIVO INTEGER NOT NULL
);
ALTER TABLE EXAMEN ADD CONSTRAINT EXAMEN_PK PRIMARY KEY (ID_EXAMEN);

CREATE TABLE RES_PRACT_USU (
    ID_RES_PRACT INTEGER NOT NULL,
    NOTA INTEGER NOT NULL,
    PREG_PRACT_ID_PREG_PRACT INTEGER NOT NULL,
    EXAMEN_ID_EXAMEN INTEGER NOT NULL
);
ALTER TABLE RES_PRACT_USU ADD CONSTRAINT RES_PRACT_USU_PK PRIMARY KEY (ID_RES_PRACT);

CREATE TABLE RES_USU (
    ID_RES_USU INTEGER NOT NULL,
    RES VARCHAR2(100) NOT NULL,
    PREG_ID_PREG INTEGER NOT NULL,
    EXAMEN_ID_EXAMEN INTEGER NOT NULL
);
ALTER TABLE RES_USU ADD CONSTRAINT RES_USU_PK PRIMARY KEY (ID_RES_USU);

-- ### 3. CREACIÓN DE LLAVES FORÁNEAS (RELACIONES)
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_DEPARTAMENTO_FK FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);

ALTER TABLE UBICACION ADD CONSTRAINT UBICACION_ESCUELA_FK FOREIGN KEY (ESCUELA_ID_ESCUELA) REFERENCES ESCUELA (ID_ESCUELA);
ALTER TABLE UBICACION ADD CONSTRAINT UBICACION_CENTRO_FK FOREIGN KEY (CENTRO_ID_CENTRO) REFERENCES CENTRO (ID_CENTRO);

ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_MUNICIPIO_FK FOREIGN KEY (MUNICIPIO_ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO);
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_UBICACION_FK FOREIGN KEY (UBICACION_ESCUELA_ID, UBICACION_CENTRO_ID) REFERENCES UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO);

ALTER TABLE EXAMEN ADD CONSTRAINT EXAMEN_REGISTRO_FK FOREIGN KEY (REGISTRO_ID_REGISTRO) REFERENCES REGISTRO (ID_REGISTRO);
ALTER TABLE EXAMEN ADD CONSTRAINT EXAMEN_CORRELATIVO_FK FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO) REFERENCES CORRELATIVO (ID_CORRELATIVO);

ALTER TABLE RES_PRACT_USU ADD CONSTRAINT RES_PRACT_USU_EXAMEN_FK FOREIGN KEY (EXAMEN_ID_EXAMEN) REFERENCES EXAMEN (ID_EXAMEN);
ALTER TABLE RES_PRACT_USU ADD CONSTRAINT RES_PRACT_USU_PREG_PRACT_FK FOREIGN KEY (PREG_PRACT_ID_PREG_PRACT) REFERENCES PREG_PRACT (ID_PREG_PRACT);

ALTER TABLE RES_USU ADD CONSTRAINT RES_USU_EXAMEN_FK FOREIGN KEY (EXAMEN_ID_EXAMEN) REFERENCES EXAMEN (ID_EXAMEN);
ALTER TABLE RES_USU ADD CONSTRAINT RES_USU_PREG_FK FOREIGN KEY (PREG_ID_PREG) REFERENCES PREG (ID_PREG);


-- Para irlo eliminando despues
DROP TABLE RESP_USU;
DROP TABLE RESP_PRACT_USU;
DROP TABLE EXAMEN;
DROP TABLE REGISTRO;
DROP TABLE UBICACION;
DROP TABLE MUNICIPIO;
DROP TABLE DEPARTAMENTO;
DROP TABLE CORRELATIVO;
DROP TABLE ESCUELA;
DROP TABLE CENTRO;
DROP TABLE PREG;
DROP TABLE PREG_PRACT;

